channels:
  - defaults  # Always leave this channel
  - conda-forge

dependencies:
  - python=3.8
  - numpy=1.21
  - matplotlib=3.4
  - jupyterlab=3.2
  - pandas=1.3
  - scikit-learn=1.0
  - scipy=1.7
  - pytest=6.2
  - flake8=3.8
  - pip=21.3  # Best to specify a version
  - pip:
      # Add packages not available for conda here
      - pandas-profiling==3.1.*
